#!/bin/bash
# S6-16 — Build signed-debug APK for PrayCalc.
#
# Produces a debug APK signed with the Android debug keystore
# (auto-generated by Gradle in ~/.android/debug.keystore).
# No secrets or release keys are required.
#
# Output: build/app/outputs/flutter-apk/app-debug.apk
#
# --- Unsigned-release APK (for external signing) ---
# The CI job in .github/workflows/release.yml produces unsigned-release APKs
# via: flutter build apk --release --no-obfuscate
# Artifact path: build/app/outputs/flutter-apk/app-release.apk
# Production signing is user-managed per D-P3-28.
#
# Usage: ./scripts/build-signed-debug.sh
#        Run from the praycalc/flutter/ directory.
#
# Requirements:
#   - Flutter SDK on PATH
#   - ANDROID_HOME or ANDROID_SDK_ROOT set
#   - Debug keystore auto-created by Gradle on first build (~/.android/debug.keystore)

set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
FLUTTER_DIR="$(dirname "$SCRIPT_DIR")"

echo "=== PrayCalc — Signed Debug APK Build ==="
echo "Flutter dir: $FLUTTER_DIR"

cd "$FLUTTER_DIR"

# Ensure Flutter is available.
if ! command -v flutter &>/dev/null; then
  echo "ERROR: flutter not found on PATH." >&2
  exit 1
fi

echo "--- Cleaning previous build artifacts ---"
flutter clean

echo "--- Getting dependencies ---"
flutter pub get

echo "--- Building signed-debug APK (debug keystore) ---"
flutter build apk --debug

APK_PATH="build/app/outputs/flutter-apk/app-debug.apk"

if [[ ! -f "$APK_PATH" ]]; then
  echo "ERROR: Expected APK not found at $APK_PATH" >&2
  exit 1
fi

APK_SIZE=$(du -sh "$APK_PATH" | cut -f1)

echo ""
echo "=== Build complete ==="
echo "Output:    $FLUTTER_DIR/$APK_PATH"
echo "Size:      $APK_SIZE"
echo ""
echo "Debug APK is signed with the auto-generated debug keystore."
echo "Not suitable for Play Store upload — use unsigned-release for external signing."
echo ""
echo "Unsigned-release APK (CI): flutter build apk --release --no-obfuscate"
echo "CI artifact path:          build/app/outputs/flutter-apk/app-release.apk"
