/**
 * Purpose: Stylesheet for MasjidMuteScreen + ZoneFormScreen (list view and
 *   add/edit form share one theme-derived StyleSheet).
 * Inputs: ThemeColors (from useThemeColors hook).
 * Outputs: createStyles(colors) -> StyleSheet.create({...}) result.
 * Constraints: Pure function of colors — no component state. Memoized by
 *   callers via useMemo(() => createStyles(colors), [colors]).
 */

import { StyleSheet } from 'react-native';
import type { ThemeColors } from '../../constants/colors';

export const createStyles = (colors: ThemeColors) => StyleSheet.create({
  container: { flex: 1, backgroundColor: colors.background.primary },
  listContent: { padding: 16, paddingBottom: 32, flexGrow: 1 },
  intro: { fontSize: 14, color: colors.text.secondary, lineHeight: 20, marginBottom: 16 },
  masterCard: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    backgroundColor: colors.background.secondary,
    borderRadius: 14,
    padding: 16,
    marginBottom: 12,
    minHeight: 64,
  },
  masterLeft: { flex: 1, marginRight: 12 },
  masterLabel: { fontSize: 16, fontWeight: '600', color: colors.text.primary },
  masterSub: { fontSize: 13, color: colors.text.muted, marginTop: 2 },
  infoCard: {
    backgroundColor: colors.background.card,
    borderRadius: 10,
    padding: 12,
    marginBottom: 12,
  },
  infoText: { fontSize: 12, color: colors.text.secondary, lineHeight: 18 },
  zonesHeadingRow: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    marginTop: 8,
    marginBottom: 8,
  },
  zonesHeading: { fontSize: 18, fontWeight: '700', color: colors.text.primary },
  addBtn: {
    paddingVertical: 8,
    paddingHorizontal: 12,
    borderRadius: 8,
    backgroundColor: colors.brand.mid,
    minHeight: 36,
    justifyContent: 'center',
  },
  addBtnText: { fontSize: 13, fontWeight: '700', color: colors.text.inverse },
  zoneRow: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    backgroundColor: colors.background.secondary,
    borderRadius: 14,
    padding: 16,
    marginBottom: 12,
    minHeight: 64,
    gap: 12,
  },
  zoneInfo: { flex: 1 },
  zoneLabel: { fontSize: 16, fontWeight: '600', color: colors.text.primary },
  zoneSub: { fontSize: 13, color: colors.text.muted, marginTop: 2 },
  zoneActive: { fontSize: 12, color: colors.state.success, fontWeight: '700', marginTop: 4 },
  deleteBtn: {
    width: 40,
    height: 40,
    borderRadius: 20,
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: colors.background.card,
  },
  deleteBtnText: { fontSize: 16, color: colors.state.error, fontWeight: '700' },

  // Form styles
  formScroll: { padding: 16, paddingBottom: 48, gap: 4 },
  formTitle: { fontSize: 22, fontWeight: '800', color: colors.text.primary, marginBottom: 16 },
  fieldLabel: { fontSize: 13, fontWeight: '600', color: colors.text.secondary, marginTop: 12, marginBottom: 6 },
  input: {
    backgroundColor: colors.background.secondary,
    borderRadius: 10,
    paddingHorizontal: 14,
    paddingVertical: 10,
    fontSize: 16,
    color: colors.text.primary,
    borderWidth: 1,
    borderColor: colors.background.card,
    minHeight: 44,
  },
  searchRow: { flexDirection: 'row', gap: 8, alignItems: 'center' },
  searchInput: { flex: 1 },
  searchBtn: {
    paddingHorizontal: 16,
    height: 44,
    borderRadius: 10,
    backgroundColor: colors.brand.mid,
    alignItems: 'center',
    justifyContent: 'center',
  },
  searchBtnText: { color: colors.text.inverse, fontWeight: '700', fontSize: 14 },
  resultRow: {
    paddingVertical: 10,
    paddingHorizontal: 12,
    backgroundColor: colors.background.card,
    borderRadius: 8,
    marginTop: 6,
  },
  resultText: { fontSize: 14, color: colors.text.primary },
  currentLocationBtn: { marginTop: 12, paddingVertical: 10, minHeight: 44, justifyContent: 'center', alignItems: 'center' },
  currentLocationText: { fontSize: 14, color: colors.brand.dark, fontWeight: '600' },
  mapFollowUpNote: { fontSize: 11, color: colors.text.muted, fontStyle: 'italic', marginTop: 8, textAlign: 'center' },
  manualToggleRow: { marginTop: 16, alignItems: 'center', minHeight: 32, justifyContent: 'center' },
  manualToggleText: { fontSize: 13, color: colors.brand.dark, fontWeight: '600' },
  manualRow: { flexDirection: 'row', gap: 12 },
  manualCol: { flex: 1 },
  radiusRow: { flexDirection: 'row', alignItems: 'center', justifyContent: 'center', gap: 20, marginTop: 4 },
  stepperBtn: {
    width: 44,
    height: 44,
    borderRadius: 22,
    backgroundColor: colors.background.card,
    alignItems: 'center',
    justifyContent: 'center',
  },
  stepperBtnText: { fontSize: 22, fontWeight: '700', color: colors.text.primary },
  radiusValue: { fontSize: 20, fontWeight: '700', color: colors.text.primary, minWidth: 80, textAlign: 'center' },
  radiusHint: { fontSize: 12, color: colors.text.muted, textAlign: 'center', marginTop: 8 },
  errorText: { fontSize: 13, color: colors.state.error, marginTop: 12, textAlign: 'center' },
  formActions: { flexDirection: 'row', gap: 12, marginTop: 24 },
  formBtn: { flex: 1, minHeight: 48, borderRadius: 10, alignItems: 'center', justifyContent: 'center' },
  formBtnPrimary: { backgroundColor: colors.brand.mid },
  formBtnPrimaryText: { color: colors.text.inverse, fontWeight: '700', fontSize: 16 },
  formBtnSecondary: { backgroundColor: colors.background.card },
  formBtnSecondaryText: { color: colors.text.primary, fontWeight: '600', fontSize: 16 },
});
