import 'dart:convert';

import 'package:flutter/services.dart' show rootBundle;
import 'package:path/path.dart' as p;
import 'package:path_provider/path_provider.dart';
import 'package:sqflite/sqflite.dart';

import '../../shared/models/settings_model.dart';

/// SQLite-backed city database service.
///
/// Data source: assets/data/cities.json (50K+ cities, generated by
/// scripts/gen_city_db.js from geo.json).
///
/// PC-3.7: bundle format — JSON asset loaded once, inserted into SQLite on
/// first run, then queried by prefix for fast search.
class CityDbService {
  static CityDbService? _instance;
  Database? _db;

  CityDbService._();

  static CityDbService get instance {
    _instance ??= CityDbService._();
    return _instance!;
  }

  Future<Database> get _database async {
    if (_db != null) return _db!;
    _db = await _openDatabase();
    return _db!;
  }

  Future<Database> _openDatabase() async {
    final dir = await getApplicationDocumentsDirectory();
    final path = p.join(dir.path, 'cities_v1.db');
    return openDatabase(
      path,
      version: 1,
      onCreate: _onCreate,
    );
  }

  Future<void> _onCreate(Database db, int version) async {
    await db.execute('''
      CREATE TABLE cities (
        id INTEGER PRIMARY KEY,
        name TEXT NOT NULL,
        country TEXT NOT NULL,
        state TEXT,
        lat REAL NOT NULL,
        lng REAL NOT NULL,
        timezone TEXT NOT NULL,
        population INTEGER
      )
    ''');
    await db.execute('CREATE INDEX idx_name ON cities(name COLLATE NOCASE)');

    // Load city data from bundled JSON asset
    final raw = await rootBundle.loadString('assets/data/cities.json');
    final List<dynamic> cities = jsonDecode(raw) as List;
    final batch = db.batch();
    for (final c in cities) {
      batch.insert('cities', {
        'name':       c['name'] as String,
        'country':    c['country'] as String,
        'state':      c['state'] as String?,
        'lat':        (c['lat'] as num).toDouble(),
        'lng':        (c['lng'] as num).toDouble(),
        'timezone':   c['timezone'] as String,
        'population': c['population'] as int? ?? 0,
      });
    }
    await batch.commit(noResult: true);
  }

  /// Search cities by name prefix (case-insensitive). Returns up to [limit] results,
  /// ordered by population descending so major cities appear first.
  Future<List<City>> search(String query, {int limit = 30}) async {
    if (query.trim().isEmpty) return [];
    final db = await _database;
    final rows = await db.rawQuery(
      '''
      SELECT name, country, state, lat, lng, timezone
      FROM cities
      WHERE name LIKE ?
      ORDER BY population DESC
      LIMIT ?
      ''',
      ['${query.trim()}%', limit],
    );
    return rows.map(_rowToCity).toList();
  }

  City _rowToCity(Map<String, Object?> row) => City(
        name:     row['name'] as String,
        country:  row['country'] as String,
        state:    row['state'] as String?,
        lat:      row['lat'] as double,
        lng:      row['lng'] as double,
        timezone: row['timezone'] as String,
      );
}
