/// PC-3.2: Validate pray_calc_dart against Node.js pray-calc reference values.
///
/// Usage:
///   dart run tool/validate.dart [--json]
///
/// Reads tool/reference.json (generated by gen_reference.mjs).
/// Compares each case's prayer times against our Dart implementation.
/// Tolerance: 1 second = 1/3600 h ≈ 0.000278 h.
///
/// Exit code 0 = all pass, 1 = failures found.
library;

import 'dart:convert';
import 'dart:io';

import 'package:pray_calc_dart/pray_calc_dart.dart';

const double _kToleranceH = 1.0 / 3600.0; // 1 second in fractional hours

void main(List<String> args) {
  final bool jsonMode = args.contains('--json');

  final scriptDir = File(Platform.script.toFilePath()).parent.path;
  final refFile = File('$scriptDir/reference.json');

  if (!refFile.existsSync()) {
    stderr.writeln('ERROR: ${refFile.path} not found.');
    stderr.writeln('Run: node tool/gen_reference.mjs > tool/reference.json');
    exit(2);
  }

  final List<dynamic> cases = jsonDecode(refFile.readAsStringSync()) as List;

  final results = <Map<String, dynamic>>[];
  int passed = 0;
  int failed = 0;
  int skipped = 0; // NaN cases

  for (final c in cases) {
    final id = c['id'] as int;
    final city = c['city'] as String;
    final dateStr = c['date'] as String;
    final lat = (c['lat'] as num).toDouble();
    final lng = (c['lng'] as num).toDouble();
    final tz = (c['tz'] as num).toDouble();
    final hanafi = c['hanafi'] as bool;
    final expected = c['expected'] as Map<String, dynamic>;

    // Parse date as UTC noon (same convention as JS Date('YYYY-MM-DDT12:00:00Z'))
    final parts = dateStr.split('-').map(int.parse).toList();
    final date = DateTime.utc(parts[0], parts[1], parts[2], 12);

    final PrayerTimes dart;
    try {
      dart = getTimes(date, lat, lng, tz, hanafi: hanafi);
    } catch (e) {
      results.add({
        'id': id,
        'city': city,
        'date': dateStr,
        'hanafi': hanafi,
        'status': 'ERROR',
        'error': e.toString(),
      });
      failed++;
      continue;
    }

    // Compare each field
    final fields = {
      'fajr': dart.fajr,
      'sunrise': dart.sunrise,
      'noon': dart.noon,
      'dhuhr': dart.dhuhr,
      'asr': dart.asr,
      'maghrib': dart.maghrib,
      'isha': dart.isha,
      'qiyam': dart.qiyam,
    };

    final fieldErrors = <String, Map<String, double>>{};
    bool casePass = true;
    bool caseSkipped = false;

    for (final entry in fields.entries) {
      final field = entry.key;
      final dartVal = entry.value;
      final jsVal = (expected[field] as num).toDouble();

      if (jsVal.isNaN || jsVal.isInfinite) {
        // JS says unreachable — we allow NaN from Dart too
        if (!dartVal.isNaN) {
          fieldErrors[field] = {
            'js': jsVal,
            'dart': dartVal,
            'diffSec': double.nan,
          };
          casePass = false;
        } else {
          caseSkipped = true;
        }
        continue;
      }

      if (dartVal.isNaN || dartVal.isInfinite) {
        fieldErrors[field] = {
          'js': jsVal,
          'dart': dartVal,
          'diffSec': double.nan,
        };
        casePass = false;
        continue;
      }

      // Normalise qiyam: both values should be in [0,24). Handle midnight wraps.
      double d = dartVal;
      double j = jsVal;
      // Bring both into same 24-hour period for comparison
      // (Qiyam can be < isha because it wraps past midnight)
      double diff = (d - j).abs();
      // Wrap-around: if diff > 12h, they're on opposite sides of midnight
      if (diff > 12.0) diff = (24.0 - diff).abs();
      final diffSec = diff * 3600.0;

      if (diff > _kToleranceH) {
        fieldErrors[field] = {
          'js': j,
          'dart': d,
          'diffSec': diffSec,
        };
        casePass = false;
      }
    }

    if (caseSkipped && fieldErrors.isEmpty) {
      skipped++;
      results.add({
        'id': id,
        'city': city,
        'date': dateStr,
        'hanafi': hanafi,
        'status': 'SKIP',
        'note': 'Polar/unreachable',
      });
    } else if (casePass) {
      passed++;
      results.add({
        'id': id,
        'city': city,
        'date': dateStr,
        'hanafi': hanafi,
        'status': 'PASS',
      });
    } else {
      failed++;
      results.add({
        'id': id,
        'city': city,
        'date': dateStr,
        'hanafi': hanafi,
        'status': 'FAIL',
        'errors': fieldErrors.map((k, v) => MapEntry(k, {
              'js': v['js']!.toStringAsFixed(6),
              'dart': v['dart']!.toStringAsFixed(6),
              'diffSec': v['diffSec']!.toStringAsFixed(2),
            })),
      });
    }
  }

  if (jsonMode) {
    print(const JsonEncoder.withIndent('  ').convert({
      'summary': {
        'total': cases.length,
        'passed': passed,
        'failed': failed,
        'skipped': skipped,
      },
      'cases': results,
    }));
  } else {
    // Human-readable summary
    stdout.writeln('pray_calc_dart validation — ${cases.length} cases');
    stdout.writeln('─' * 50);
    stdout.writeln('  Passed : $passed');
    stdout.writeln('  Failed : $failed');
    stdout.writeln('  Skipped: $skipped (polar / unreachable)');
    stdout.writeln('─' * 50);

    if (failed > 0) {
      stdout.writeln('\nFAILURES:');
      for (final r in results) {
        if (r['status'] != 'FAIL') continue;
        final errors = r['errors'] as Map;
        stdout.writeln(
          '  [${r["id"]}] ${r["city"]}  ${r["date"]}  hanafi=${r["hanafi"]}',
        );
        for (final e in errors.entries) {
          final v = e.value as Map;
          stdout.writeln(
            '      ${e.key}: js=${v["js"]}  dart=${v["dart"]}  Δ=${v["diffSec"]}s',
          );
        }
      }
      stdout.writeln('');
    }

    if (failed == 0) {
      stdout.writeln('\n✓ All ${passed + skipped} cases pass (≤1 second tolerance)');
    }
  }

  exit(failed > 0 ? 1 : 0);
}
