name: Sync Wiki

on:
  push:
    branches: [main]
    paths: ['.github/wiki/**']

jobs:
  sync:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v4
      - uses: Andrew-Chen-Wang/github-wiki-action@v4
        with:
          path: '.github/wiki'
          token: ${{ secrets.GITHUB_TOKEN }}
